### ISSUE TITLE
Refactor yeoman generators to remove the use of NamedBase

### ISSUE THREAD

**Issue by johngully** [patternpack/generator-patternpack#3]
Yeoman has deprecated the use of `generators.NamedBase` with https://github.com/yeoman/generator/issues/882. The PatternPack generators should be refactored to `generators.Base`

**Comment by francbartoli** [comment]
Hi @johngully, are you facing this same error below?

`events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/geobart/Development/my-pattern-geobeyond/dist/_gitkeep
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as move] (/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at constructor.create (/usr/local/lib/node_modules/generator-patternpack/init/index.js:40:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-patternpack/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/local/lib/node_modules/generator-patternpack/node_modules/run-async/index.js:24:25
    at /usr/local/lib/node_modules/generator-patternpack/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

**Comment by johngully** [comment]
Thanks for reporting.  Can you provide the steps to reproduce this in a NEW issue?

**Comment by francbartoli** [comment]
done #4 

Thx
