### ISSUE TITLE
Copy from a source that does not exist

### ISSUE THREAD

**Issue by francbartoli** [patternpack/generator-patternpack#4]
Steps to reproduce:
- [ init]  `yo patternpack:init my-pattern-library`
- [ description] `(!) NamedBase constructor is deprecated. See https://github.com/yeoman/generator/issues/882
  (!) NamedBase constructor is deprecated. See https://github.com/yeoman/generator/issues/882
  ? Provide a description of the pattern library My pattern Library`

events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/geobart/Development/my-pattern-geobeyond/dist/_gitkeep
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as move](/usr/local/lib/node_modules/generator-patternpack/node_modules/mem-fs-editor/lib/actions/move.js:4:8)
    at constructor.create (/usr/local/lib/node_modules/generator-patternpack/init/index.js:40:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-patternpack/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/local/lib/node_modules/generator-patternpack/node_modules/run-async/index.js:24:25
    at /usr/local/lib/node_modules/generator-patternpack/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by johngully** [comment]
Are you on Windows, Mac or Linux?

**Comment by francbartoli** [comment]
Mac OS X 10.9.5

**Comment by johngully** [comment]
Found the bug and squashed it.  Please install the new version of `generator-patternpack` 0.9.1

**Comment by francbartoli** [comment]
Hey @johngully, just got the new version and not it works like a charm!

Thanks for this excellent tool.
